### ISSUE TITLE
Version 0.3.0 of GitHub's official light syntax theme breaks

### ISSUE THREAD

**Issue by freshteapot** [primer/github-syntax-theme-generator#17]
Hello,

I see a new version was pushed yesterday. I can confirm that today. rolling back to 0.2.0 allows me to see my theme.

```
apm install github-atom-light-syntax@0.2.0
```

Reference:
- https://github.com/primer/github-atom-light-syntax

**Comment by javan** [comment]
Same here. After updating to 0.3.0 I lost all syntax highlighting in Atom. Rolling back to 0.2.0 restored it.

**Comment by diogo-gomes** [comment]
Same with dark theme.

@freshteapot, can you change title to "light/dark syntax"?

**Comment by jonrohan** [comment]
I'll see what happened today and hopefully get a fix out

**Comment by jonrohan** [comment]
I've reverted to the stylesheet from `0.2.0` something is up with the apm tm to atom theme conversion. I'm going to try and rewrite it so we're outputting directly from source. #7 

Should be fixed now.

**Comment by freshteapot** [comment]
@diogo-gomes done (sorry for the delay)
@jonrohan Can confirm 0.3.2 works :)

Love the theme.
