### ISSUE TITLE
Version 0.3.2 does not mark changed lines in Atom

### ISSUE THREAD

**Issue by philipp-germann** [primer/github-syntax-theme-generator#19]
After upgrading github-atom-light-syntax to 0.3.2 the marks indicating changed lines disappeared.

Default theme:
![image](https://cloud.githubusercontent.com/assets/8821566/21045877/65e4e900-be02-11e6-8d15-c34b920f3675.png)

GitHub Atom light v0.3.2:
![image](https://cloud.githubusercontent.com/assets/8821566/21045946/a3032ff4-be02-11e6-835f-cedeaf309b7b.png)

I am using Atom 1.12.6 on Ubuntu 16.04.

**Comment by jonrohan** [comment]
Thanks for the report, possibly a variable I didn't name correctly

**Comment by jonrohan** [comment]
![image](https://cloud.githubusercontent.com/assets/54012/21051199/19c0547a-bded-11e6-8198-7feb8f15091e.png)

Actually, they are there, just a poor color choice. Will update to a better color
