### ISSUE TITLE
Deprecations: contents of atom-text-editor elements are no longer encapsulated within a shadow DOM boundary

### ISSUE THREAD

**Issue by diogo-gomes** [primer/github-syntax-theme-generator#37]
Starting from Atom v1.13.0, the contents of `atom-text-editor` elements are no longer encapsulated within a shadow DOM boundary.
This means you should stop using `:host` and `::shadow` pseudo-selectors, and prepend all your syntax selectors with `syntax--`.

To prevent breakage with existing style sheets, Atom will automatically upgrade the following selectors:

- atom-text-editor, :host => atom-text-editor,atom-text-editor
- atom-text-editor .line.cursor-line, :host .line.cursor-line => atom-text-editor .line.cursor-line,atom-text-editor .line.cursor-line
- atom-text-editor .invisible, :host .invisible => atom-text-editor .invisible,atom-text-editor .invisible
- atom-text-editor .cursor, :host .cursor => atom-text-editor .cursor,atom-text-editor .cursor
- atom-text-editor .selection .region, :host .selection .region => atom-text-editor .selection .region,atom-text-editor .selection .region
- atom-text-editor .bracket-matcher .region, :host .bracket-matcher .region => atom-text-editor .bracket-matcher .region,atom-text-editor .bracket-matcher .region
- atom-text-editor .invisible-character, :host .invisible-character => atom-text-editor .invisible-character,atom-text-editor .invisible-character
- atom-text-editor .indent-guide, :host .indent-guide => atom-text-editor .indent-guide,atom-text-editor .indent-guide
- atom-text-editor .wrap-guide, :host .wrap-guide => atom-text-editor .wrap-guide,atom-text-editor .wrap-guide
- atom-text-editor .gutter, :host .gutter => atom-text-editor .gutter,atom-text-editor .gutter
- atom-text-editor .gutter .line-number, :host .gutter .line-number => atom-text-editor .gutter .line-number,atom-text-editor .gutter .line-number
- atom-text-editor .gutter .line-number.cursor-line, :host .gutter .line-number.cursor-line => atom-text-editor .gutter .line-number.cursor-line,atom-text-editor .gutter .line-number.cursor-line
- atom-text-editor .gutter .line-number.cursor-line-no-selection, :host .gutter .line-number.cursor-line-no-selection => atom-text-editor .gutter .line-number.cursor-line-no-selection,atom-text-editor .gutter .line-number.cursor-line-no-selection
- atom-text-editor .gutter .line-number .icon-right, :host .gutter .line-number .icon-right => atom-text-editor .gutter .line-number .icon-right,atom-text-editor .gutter .line-number .icon-right
- atom-text-editor .gutter:not(.git-diff-icon) .line-number.git-line-removed.git-line-removed::before, :host .gutter:not(.git-diff-icon) .line-number.git-line-removed.git-line-removed::before => atom-text-editor .gutter:not(.git-diff-icon) .line-number.git-line-removed.git-line-removed::before,atom-text-editor .gutter:not(.git-diff-icon) .line-number.git-line-removed.git-line-removed::before
- atom-text-editor .gutter:not(.git-diff-icon) .line-number.git-line-removed::after, :host .gutter:not(.git-diff-icon) .line-number.git-line-removed::after => atom-text-editor .gutter:not(.git-diff-icon) .line-number.git-line-removed::after,atom-text-editor .gutter:not(.git-diff-icon) .line-number.git-line-removed::after
- atom-text-editor .gutter .line-number.folded, :host .gutter .line-number.folded, atom-text-editor .gutter .line-number:after, :host .gutter .line-number:after, atom-text-editor .fold-marker:after, :host .fold-marker:after => atom-text-editor .gutter .line-number.folded,atom-text-editor .gutter .line-number.folded, atom-text-editor .gutter .line-number:after,atom-text-editor .gutter .line-number:after, atom-text-editor .fold-marker:after,atom-text-editor .fold-marker:after
- atom-text-editor .search-results .marker .region, :host .search-results .marker .region => atom-text-editor .search-results .syntax--marker .region,atom-text-editor .search-results .syntax--marker .region
- atom-text-editor .search-results .marker.current-result .region, :host .search-results .marker.current-result .region => atom-text-editor .search-results .syntax--marker.current-result .region,atom-text-editor .search-results .syntax--marker.current-result .region
- .comment, .punctuation.definition.comment, .string.comment => .syntax--comment, .syntax--punctuation.syntax--definition.syntax--comment, .syntax--string.syntax--comment
- .constant, .entity.name.constant, .variable.other.constant, .variable.language => .syntax--constant, .syntax--entity.syntax--name.syntax--constant, .syntax--variable.syntax--other.syntax--constant, .syntax--variable.syntax--language
- .entity, .entity.name => .syntax--entity, .syntax--entity.syntax--name
- .variable.parameter.function => .syntax--variable.syntax--parameter.syntax--function
- .entity.name.tag => .syntax--entity.syntax--name.syntax--tag
- .keyword => .syntax--keyword
- .storage, .storage.type => .syntax--storage, .syntax--storage.syntax--type
- .storage.modifier.package, .storage.modifier.import, .storage.type.java => .syntax--storage.syntax--modifier.syntax--package, .syntax--storage.syntax--modifier.syntax--import, .syntax--storage.syntax--type.syntax--java
- .string, .punctuation.definition.string, .string .punctuation.section.embedded .source => .syntax--string, .syntax--punctuation.syntax--definition.syntax--string, .syntax--string .syntax--punctuation.syntax--section.syntax--embedded .syntax--source
- .support => .syntax--support
- .meta.property-name => .syntax--meta.syntax--property-name
- .variable => .syntax--variable
- .variable.other => .syntax--variable.syntax--other
- .invalid.broken => .syntax--invalid.syntax--broken
- .invalid.deprecated => .syntax--invalid.syntax--deprecated
- .invalid.illegal => .syntax--invalid.syntax--illegal
- .invalid.unimplemented => .syntax--invalid.syntax--unimplemented
- .message.error => .syntax--message.syntax--error
- .string .source => .syntax--string .syntax--source
- .string .variable => .syntax--string .syntax--variable
- .source.regexp, .string.regexp => .syntax--source.syntax--regexp, .syntax--string.syntax--regexp
- .string.regexp.character-class, .string.regexp .constant.character.escape, .string.regexp .source.ruby.embedded, .string.regexp .string.regexp.arbitrary-repitition => .syntax--string.syntax--regexp.syntax--character-class, .syntax--string.syntax--regexp .syntax--constant.syntax--character.syntax--escape, .syntax--string.syntax--regexp .syntax--source.syntax--ruby.syntax--embedded, .syntax--string.syntax--regexp .syntax--string.syntax--regexp.syntax--arbitrary-repitition
- .string.regexp .constant.character.escape => .syntax--string.syntax--regexp .syntax--constant.syntax--character.syntax--escape
- .support.constant => .syntax--support.syntax--constant
- .support.variable => .syntax--support.syntax--variable
- .meta.module-reference => .syntax--meta.syntax--module-reference
- .markup.list => .syntax--markup.syntax--list
- .markup.heading, .markup.heading .entity.name => .syntax--markup.syntax--heading, .syntax--markup.syntax--heading .syntax--entity.syntax--name
- .markup.quote => .syntax--markup.syntax--quote
- .markup.italic => .syntax--markup.syntax--italic
- .markup.bold => .syntax--markup.syntax--bold
- .markup.raw => .syntax--markup.syntax--raw
- .markup.deleted, .meta.diff.header.from-file, .punctuation.definition.deleted => .syntax--markup.syntax--deleted, .syntax--meta.syntax--diff.syntax--header.syntax--from-file, .syntax--punctuation.syntax--definition.syntax--deleted
- .markup.inserted, .meta.diff.header.to-file, .punctuation.definition.inserted => .syntax--markup.syntax--inserted, .syntax--meta.syntax--diff.syntax--header.syntax--to-file, .syntax--punctuation.syntax--definition.syntax--inserted
- .markup.changed, .punctuation.definition.changed => .syntax--markup.syntax--changed, .syntax--punctuation.syntax--definition.syntax--changed
- .markup.ignored, .markup.untracked => .syntax--markup.syntax--ignored, .syntax--markup.untracked
- .meta.diff.range => .syntax--meta.syntax--diff.syntax--range
- .meta.diff.header => .syntax--meta.syntax--diff.syntax--header
- .meta.separator => .syntax--meta.syntax--separator
- .meta.output => .syntax--meta.syntax--output
- .brackethighlighter.tag, .brackethighlighter.curly, .brackethighlighter.round, .brackethighlighter.square, .brackethighlighter.angle, .brackethighlighter.quote => .brackethighlighter.syntax--tag, .brackethighlighter.syntax--curly, .brackethighlighter.syntax--round, .brackethighlighter.syntax--square, .brackethighlighter.syntax--angle, .brackethighlighter.syntax--quote
- .sublimelinter.mark.error => .sublimelinter.syntax--mark.syntax--error
- .sublimelinter.mark.warning => .sublimelinter.syntax--mark.syntax--warning
- .constant.other.reference.link, .string.other.link => .syntax--constant.syntax--other.syntax--reference.syntax--link, .syntax--string.syntax--other.syntax--link

Automatic translation of selectors will be removed in a few release cycles to minimize startup time. Please, make sure to upgrade the above selectors as soon as possible.

**Comment by kockok** [comment]
+1 here, is the problem solved yet?
