### ISSUE TITLE
In Atom bracket matcher does not highlight brackets on the same line

### ISSUE THREAD

**Issue by bojand** [primer/github-syntax-theme-generator#41]
Atom: 1.13.1x64
OS X El Capitan 10.11.6
All atom packages up to date.
No custom CCS styles.
Syntax theme: github-atom-light-syntax

I am not sure if this is Atom bug somehow, but it only happens for me with github-atom-light-syntax syntax theme, so I think it belongs here possibly.

The brackets on same line do not seem to be matched. Different lines do match. Notice the match (with bottom border).

![atom-github-light](https://cloud.githubusercontent.com/assets/2081100/22692438/72b409f8-ed15-11e6-8fb0-f67921919dab.gif)

This happens regardless of the type of bracket. 

Expected look with stock atom One Light theme:

![atom-onelight](https://cloud.githubusercontent.com/assets/2081100/22692448/8c101ffe-ed15-11e6-9260-f17354493780.gif)

**Comment by lee-dohm** [comment]
It looks like the `atom-text-editor .line.cursor-line` style is showing up in front of the bracket-matcher decoration. When I disable the `background-color` on the `cursor-line` style, the bracket-matcher decoration shows. It appears that the `cursor-line` style in the default themes is transparent:

<img width="469" alt="screen shot 2017-02-08 at 12 31 57 pm" src="https://cloud.githubusercontent.com/assets/1038121/22756236/4e9b91c6-edfb-11e6-8045-91f21f8a9369.png">

whereas the one in the primer themes is opaque:

<img width="489" alt="screen shot 2017-02-08 at 12 33 08 pm" src="https://cloud.githubusercontent.com/assets/1038121/22756262/5b73ff32-edfb-11e6-8e0f-64e5ede220f0.png">

**Comment by cmwinters** [comment]
@simurai would you be able to take a look at this?

**Comment by bojand** [comment]
Sorry to bring this up again... while the latest 0.5.0 release did technically fix this specific issue, it did make matching somewhat worse; at least aesthetically?

Atom: 1.18.0 x64
OS X El Capitan 10.12.5
All atom packages up to date.
No custom CCS styles.
Syntax theme: github-atom-light-syntax

![bracket_issue](https://user-images.githubusercontent.com/2081100/27192210-d22bb898-51d0-11e7-9a16-0aa09816a615.gif)

Not sure what's going on here, seems like the foreground text color is too light or matches the background one now. Or something. 

Let me know if I should create a new issue.

**Comment by simurai** [comment]
I can't reproduce that slightly bluer background:

![background](https://user-images.githubusercontent.com/378023/27212059-8ce7033c-5298-11e7-89a5-8bd78da87471.gif)

 If you paste the following in your `styles.less` file, does it remove the background?

```less
atom-text-editor .bracket-matcher,
atom-text-editor .bracket-matcher .region {
  background-color: transparent !important;
}
```

**Comment by bojand** [comment]
Hmm somehow it seems _I did_ have custom colour for background bracket matcher in the stylesheet... I don't remember ever experimenting with it at all... but I must have... maybe it was when I was debugging the original issue and forgot to remove it or something. 

```
atom-text-editor.editor .bracket-matcher .region {
  background-color: #e6f5ff;
}
```

When I remove that it seems to work fine. Sorry my bad.
