### ISSUE TITLE
Deprecated+selector+in+`github-atom-light-syntax/index.less`

### ISSUE THREAD

**Issue by wadi-chemkhi** [primer/github-syntax-theme-generator#46]
there is deprecation warning on atom 1.15.0 for using shadow selectors.
with the description :

>  Starting from Atom v1.13.0, the contents of atom-text-editor elements are no longer encapsulated within a shadow DOM boundary. This means you should stop using :host and ::shadow pseudo-selectors, and prepend all your syntax selectors with syntax--.

**Comment by jordanbrauer** [comment]
I am experiencing the same issue.

The issue has been fixed and pulled into master AFAIK from [#4](https://github.com/primer/github-atom-light-syntax/pull/4) on the syntax theme repo.

I'm not sure why this has not been released yet though .......

**Comment by jonrohan** [comment]
New release is out
