### ISSUE TITLE
Conflict with the Atom github package

### ISSUE THREAD

**Issue by bdubaut** [primer/github-syntax-theme-generator#56]
When using `github-syntax-light` or `github-syntax-dark`, there is a colour issue with the `github` package when solving conflicts, it is just unreadable:
### Current conflict resolution style
<img width="414" alt="screen shot 2017-08-16 at 08 55 01" src="https://user-images.githubusercontent.com/798319/29351027-3ad5e376-8261-11e7-90fb-0a59aa4e8e45.png">
<img width="674" alt="screen shot 2017-08-16 at 08 54 35" src="https://user-images.githubusercontent.com/798319/29351036-41b18b6e-8261-11e7-818e-bf4f6352b5f1.png">

### Expected result
If we compare with `one-light` or `one-dark`:
<img width="498" alt="screen shot 2017-08-16 at 09 01 55" src="https://user-images.githubusercontent.com/798319/29351109-96d02a88-8261-11e7-84e6-0a61653ec636.png">
<img width="465" alt="screen shot 2017-08-16 at 09 01 43" src="https://user-images.githubusercontent.com/798319/29351115-9c8873ea-8261-11e7-890d-d6e2b2b4b9cb.png">

**Comment by jonrohan** [comment]
Can you share which UI you're using?

**Comment by bdubaut** [comment]
@jonrohan I am using one-dark-ui and one-light-ui
