### ISSUE TITLE
Visual Studio Code links are dead

### ISSUE THREAD

**Issue by karol-majewski** [primer/github-syntax-theme-generator#61]
The links from the README don't work anymore:

https://github.com/primer/github-vscode-syntax-light
https://github.com/primer/github-vscode-syntax-dark

Both return 404.

**Comment by emplums** [comment]
Thanks for the heads up @karol-majewski and sorry for the late response! Those repos are actually empty, so we need to remove the links from the README.

**Comment by karol-majewski** [comment]
@emplums Thank you for getting back. Are there any plans to make these themes open for public consumption?

**Comment by emplums** [comment]
Hey @karol-majewski those themes don't exist yet - I'm not sure if we've got any plans to create them as of now!

**Comment by yunlingz** [comment]
@emplums @karol-majewski
I have created a theme for vs code based on github's light color theme: 
* <https://github.com/Hyzeta/vscode-theme-github-light>
* <https://marketplace.visualstudio.com/items?itemName=Hyzeta.vscode-theme-github-light>
Maybe you can take a look at this. :bowtie::bowtie::bowtie:
